// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Counter: typeof import('./../../src/components/counter.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElMain: typeof import('element-plus/es')['ElMain']
    'IFluentMdl2:acceptMedium': typeof import('~icons/fluent/mdl2-accept-medium')['default']
    IFluentMdl2AcceptMedium: typeof import('~icons/fluent/mdl2-accept-medium')['default']
    IMaterialSymbols123: typeof import('~icons/material-symbols/123')['default']
    'IMdi:accountBoxMultiple': typeof import('~icons/mdi/account-box-multiple')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
